### PR TITLE
Separate authentication and authorization

### PR DESCRIPTION
**Pull request by mjbrisebois**
This separation of responsibilities is more flexible and simplifies the authentication requirements that are enforced by `dispatcher`.

This change allows
- each service to control user privileges
- use cookies instead of headers for transmitting authentication key
- authenticated requests where we don't control the headers (eg. websocket upgrade, static asset `GET` requests
- avoid using query params for authentcation

### CODE REVIEW

**Comment by mjbrisebois** [comment]
> In addition to that, this is completely orthogonal to decision of how to transmit signature. Sending it twice doesn't make it any easier to send it as a cookie, or do a WebSocket upgrade.

It is not being sent twice, it is being sent in 2 different ways for 2 different concepts.  By moving the complex payload signing into the Admin API we can reliably assume we have control over the headers.  Where as with WebSocket upgrade and static assets, we cannot control the header.

**Comment by samrose** [comment]
@yegortimoshenko wrote

> Signatures as a concept can only handle authentication, and signing a payload does not make it authorization. 

To expand on this: it can be proposed that the likely requirements for this component are:

authentication only. There is no authorization context in the architecture for this component. The system as proposed by @yegortimoshenko actually only focuses on authentication. So it is already separate. 

ensure that the message was not tampered with during transit. 

"Authorization" contexts for software running on holoports would be handled by applications from what I understand

**Comment by peeech** [comment]
First of all I am adding a business requirement to this PR: Deadline. Needs to be decided and merged by monday morning CET.

**Comment by peeech** [comment]
Secondly can we move the discussion about authorization vs authentication to https://english.stackexchange.com/?

Our security requirement is:
"As an HPOS Admin I can communicate with my HoloPort across internet and nobody else can" which in my opinion directly translates to the dialogue:
- Hey I'm `Zvvi6c3JIiAOG2qTR4YbeyRSjoweENYvCFT+Bx3otFw` and I want to `GET /v1/config`
- Yeah sure. Can you prove it?
- Yep, here is my signature.

Nothing else. Static files can't be protected that way because it requires downloading static files to even initiate message exchange between HPOS and Host.

**Comment by yegortimoshenko** [comment]
Agree, authentication vs authorization terminology is a red herring.

"Hey, I am an admin and as of Dec 13, 2019 I want to access GET /api/v1/config" would be a reasonable signature. OTOH, "I am an admin, as of is Dec 13, 2019" isn't a good payload to sign, and it's analogous to signing a blank check with date on it.

I feel this was attempting to retrofit OAuth token pattern, which doesn't apply to public-key cryptography.

**Comment by samrose** [comment]
> Our security requirement is:
"As an HPOS Admin I can communicate with my HoloPort across internet and nobody else can" which in my opinion directly translates to the dialogue:
Hey I'm Zvvi6c3JIiAOG2qTR4YbeyRSjoweENYvCFT+Bx3otFw and I want to GET /v1/config
Yeah sure. Can you prove it?
Yep, here is my signature.
Nothing else. Static files can't be protected that way because it requires downloading static files to even initiate message exchange between HPOS and Host.

@peeech so it seems that the standard around https://tools.ietf.org/id/draft-cavage-http-signatures-08.html  meets these requirements. And http signatures is the approach that I understand @yegortimoshenko to be proposing

As for "authentication and authorization" there isn't much to debate there. 99% of people who work in this industry understand these concepts in the following ways

https://miro.medium.com/max/500/0*EGe-sdGsXYBtlmkW.png

So, if someone were to invoke these concepts in the context of this discussion, they would only need to be accurate about what the concepts relevant to, in order for it to be useful. From my understanding, the only relevant context is "authentication" based on everything discussed about the requirements so far. That's all I really had to say on it.

**Comment by mjbrisebois** [comment]
Closing in favor of #22

**Pull request closed without merging**
